env:
  es2021: true
  node: true
  jest: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  'no-underscore-dangle': [
    'error',
    {
      allow: ['__filename', '__dirname'],
    },
  ],
  import/extensions: [
    error,
    {
      js: always,
    },
  ],
  'no-console': 'off',
}
